### ISSUE TITLE
Broken links in README's Project ideas

### ISSUE THREAD

**Issue by mtabz** [w3f/Open-Grants-Program#376]
The following text on Project ideas has broken links to the Web 3.0 Technology Stack and previously accepted applications.

> An overview of existing projects in the Web 3.0 Technology Stack along with broad project ideas we would potentially be interested in funding can be found [here](https://github.com/w3f/Open-Grants-Program/blob/master/grants/polkadot_stack.md), as well as a list of previously accepted applications [here](https://github.com/w3f/Open-Grants-Program/blob/master/grants/accepted_grant_applications.md). Additionally, the Substrate Builders feedback board may contain some useful ideas for grant projects.

Instead of https://github.com/w3f/Open-Grants-Program/blob/master/grants/polkadot_stack.md I believe it should point to the [page](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md) under the General Grants program. 

Similarly, accepted applications are listed [here](https://github.com/w3f/General-Grants-Program/blob/master/grants/accepted_grant_applications.md) (unless there is a separate page for Open-Grant acceptances?).

**Comment by alxs** [comment]
Many thanks for noticing @mtabz! I'll take care of it.
