### ISSUE TITLE
Question: Adding to milestone post-application acceptance.

### ISSUE THREAD

**Issue by GamePowerDev** [w3f/Open-Grants-Program#417]
Hello! 

Our team would like to revise our milestones (add a milestone in). Since our application was already accepted we don't want to change the amount we asked for, we want to do this extra milestone of no charge to the Web3 Foundation.

However we do want to make sure this work is tracked in our application. So my question is, should we revise our application and submit a PR with the new milestone for $0. Or should we just work on this milestone outside of the application?

Thanks for any feedback.

**Comment by alxs** [comment]
Hey @GamePowerDev. Thanks for asking and yes, you can certainly add an extra milestone via PR if you also want to submit it.

**Comment by GamePowerDev** [comment]
Great! thank you, I'll get that submitted asap.
