### ISSUE TITLE
46274ef4dd8d846bf5a1cbe804e4767a91ce726e

### ISSUE THREAD

**Issue by Ebimk2** [w3f/Open-Grants-Program#491]
46274ef4dd8d846bf5a1cbe804e4767a91ce726e

_Originally posted by @Ebimk2 in https://github.com/tronprotocol/java-tron/pull/3877#issuecomment-878521187_

**Comment by Ebimk2** [comment]
Yes

**Comment by Noc2** [comment]
I’m closing this issue since it’s unrelated to the open grants program as far as I can see. If this isn’t the case feel free to add additional explanation here.
